apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-deployment1
  template:
    metadata:
      labels:
        app: my-deployment1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        